# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d282f2c3a855b052d9627b7c3f9a0ca9f24ec99fac7525cc718dab96a7d1c8fd9b16687e43ed4bd191c5ac6eb4dc54ebb088c93d2628f5c8c2a9d3a6a6106d38

test:
  secret_key_base: e5b3e2beb2d228d30e94b9817937536901043bdfda32858353970e0ef411f2fc2ffc206a682e716f3a681eeabe8a30aeeb773fcba577551957be3fb08aee45b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
